export  const articles=
[
 {title: "Louisville anti-racism protests resume amid tensions over Breonna Taylor ruling", description: "Police said 127 arrests were made in the first nig…partment would be charged with causing her death.", content: "A second night of anti-racism protests got off to … in the fatal shooting of Breonna... [5194 chars]", url: "https://www.devdiscourse.com/article/law-order/122…s-resume-amid-tensions-over-breonna-taylor-ruling", image: "https://www.devdiscourse.com/remote.axd?https://de…0_2019_20_10_47_9252159.jpg?width=920&format=jpeg"},
 {title: "Delhi Prisons DG tests COVID-19 positive", description: "Earlier, on August 21, the Delhi Prisons Departmen…he pandemic situation in jails here has improved.", content: "Director General of Delhi Prisons Sandeep Goel has…s in Delhi Prisons stood at 25, in... [405 chars]", url: "https://www.devdiscourse.com/article/health/1226901-delhi-prisons-dg-tests-covid-19-positive", image: "https://www.devdiscourse.com/remote.axd?https://de…6_2019_18_22_44_8556925.png?width=920&format=jpeg"},
 {title: "Breonna Taylor death case: Jury decision sparks series of protests across the United States", description: "None of the police officers involved in the death …lor was charged with killing, media reports said.", content: "Maybe like 1000 people here outside the Barclays C…e for an eye’ now,” says the man on... [42 chars]", url: "https://scroll.in/video/974010/breonna-taylor-deat…parks-series-of-protests-across-the-united-states", image: "https://s01.sgp1.cdn.digitaloceanspaces.com/book/148005-ofchwxxliu-1600953947.jpeg"},
{title: "Kumar Sanu's son Jaan Kumar Sanu is the first confirmed contestant", description: "Bigg Boss 14 is here to entertain everyone and thr…r first contestant, and it's none other than Jaan", content: "Even months later, this incident is being talked-a…sserted that Reshma deserves justice. Excerpts...", url: "https://timesofindia.indiatimes.com/tv/news/hindi/…rst-confirmed-contestant/articleshow/78295436.cms", image: "https://static.toiimg.com/thumb/msid-78295381,widt…_pad-40,resizemode-75,imgsize-331017/78295381.jpg"},
{title: "Two police officers shot amid Louisville protests over Breonna Taylor ruling", description: "The grand jury decided that none of the three whit…indicted on charges of endangering her neighbors.", content: "Next Generation Action Network leads a protest and…ille, Kentucky, during protests o... [6380 chars]", url: "https://indianexpress.com/article/world/louisville…eonna-taylor-ruling-police-officers-shot-6608693/", image: "https://images.indianexpress.com/2020/09/protests1.jpg"},
{title: "Vadodara: Dhumad junction continues to be a death trap for commuters", description: "Makarpura police station, which also has a stretch…pots near Jambuva but none has been unidentified.", content: "People cross the road at Dhumad junction on the Va…remains were recovered at the Dhu... [3074 chars]", url: "https://indianexpress.com/article/india/vadodara-d…ntinues-to-be-a-death-trap-for-commuters-6608352/", image: "https://images.indianexpress.com/2020/09/nh-8.jpg"},
{title: "Louisville police officers cleared of criminal charges in Breonna Taylor death", description: "Benjamin Crump, a civil rights lawyer representing…eagues forced their way in with a search warrant.", content: "Two white policemen who fired into the apartment o…eighbors, Kentucky's attorney gen... [4724 chars]", url: "https://www.devdiscourse.com/article/law-order/122…eared-of-criminal-charges-in-breonna-taylor-death", image: "https://www.devdiscourse.com/remote.axd?https://de…4_2019_17_12_02_6631371.jpg?width=920&format=jpeg"},
{title: "Egyptian orchestra for visually-impaired women resumes concerts amid coronavirus", description: "Egypt's Al Nour Wal Amal (light and hope) chamber …en to rehearse again, although in smaller groups.", content: "Egypt's Al Nour Wal Amal (light and hope) chamber …the orchestra members resumed reh... [1259 chars]", url: "https://www.devdiscourse.com/article/entertainment…-impaired-women-resumes-concerts-amid-coronavirus", image: "https://www.devdiscourse.com/remote.axd?https://de…01_2019_11_08_27_691991.jpg?width=920&format=jpeg"}
]